USE ecommerce;

CREATE TABLE cart (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INTEGER REFERENCES users(userId) ON DELETE CASCADE,
  product_id INTEGER REFERENCES products(id) ON DELETE CASCADE,
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);